### ISSUE TITLE
README should mention where the output is safe to use

### ISSUE THREAD

**Issue by twhb** [parshap/html-escape#1]
Only some HTML contexts support character references, the README should say which. Otherwise you're implying that the output is safe to use anywhere in HTML, and creating an API contract you can't honor.

How I would word it:

> The result is safe to use in Data- and RCDATA-containing elements (everything but script and style elements), single-quoted attribute values, and double-quoted attribute values, nowhere else.

Also, for the contexts you support, there's no reason to escape ">". See:
- https://html.spec.whatwg.org/multipage/syntax.html#data-state
- https://html.spec.whatwg.org/multipage/syntax.html#rcdata-state
- https://html.spec.whatwg.org/multipage/syntax.html#attribute-value-(double-quoted)-state
- https://html.spec.whatwg.org/multipage/syntax.html#attribute-value-(single-quoted)-state

**Comment by parshap** [comment]
Thanks! Happy to be more explicit and strict.

**Comment by twhb** [comment]
Happy to help, and thanks for the quick resolution.
